### PR TITLE
Feature/Implement NOOP Handler

### PR DESCRIPTION
**Pull request by rehleinBo**
* Implemented handlerNoop, tests
* Updated message
* Updated consts
* Updated readme

# PR Details

The SMTP library we use sends NOOP commands for keep alive and we use them to check ia connection is still active.

## Description

Added the NOOP command which usually replies `250 OK`

## Related Issue

This was very spontaneous. So no issue was created

## Motivation and Context

See details

## How Has This Been Tested

Unit Tests and manual integration test.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the [**CONTRIBUTING** document](https://github.com/mocktools/go-smtp-mock/blob/master/CONTRIBUTING.md)
- [x] I have added tests to cover my changes
- [x] I have run `golangci-lint run` from the root directory to see all new and existing tests pass 
  - [x]  At least no new issues
- [x] I have run `go tool cover` to avoid test coverage degradation

### CODE REVIEW

**Comment by rehleinBo** [comment]
Hi @bestwebua 

I really don't want to bother you but did you have a minute to look over the changes?

**Comment by rehleinBo** [comment]
No need to hurry anymore.  
I found another solution.

**Comment by leshachaplin** [comment]
> No need to hurry anymore. I found another solution.

Hi, could you share a founded solution please

**Comment by rehleinBo** [comment]
> Hi, could you share a founded solution please

I will
But unfortunately I'm on vacation and have no access to my work stuff...

**Comment by bestwebua** [comment]
@rehleinBo Thanks for your PR, I have added this feature into latest release. @leshachaplin You can use `smtpmock` latest version.

**Comment by rehleinBo** [comment]
> leshachaplin

Sorry for the late answer. I used mocksmtp instead. It does not give such detailed information like this package but it worked for me.

````go
import (
mocksmtp "go.goblog.app/app/pkgs/mocksmtp"
)
....
port, received, cancelFn, err = mocksmtp.StartMockSMTPServer()
....
```

**Pull request closed without merging**
